"""add created_at field to session

Revision ID: 8db8afbb9403
Revises: 8b020e2c5b54
Create Date: 2025-04-15 16:18:14.827724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db8afbb9403'
down_revision: Union[str, None] = '8b020e2c5b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.create_unique_constraint(None, 'users', ['sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('sessions', 'created_at')
    # ### end Alembic commands ###
